# Generated by Django 4.1.4 on 2022-12-08 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='deleted_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='done_at',
            field=models.DateField(null=True),
        ),
    ]
